import "@/styles/globals.css";

import { Noto_Sans_Thai } from 'next/font/google';
import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";

const fontSansNoto_Sans_Thai = Noto_Sans_Thai({
    subsets: ["latin", "thai"],
    variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${fontSansNoto_Sans_Thai.className}`}>
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
